version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules          # Para preservar node_modules dentro do container
      - ./.env:/app/.env
    ports:
      - "3001:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules          # Mantém node_modules do container intacto
      - ./.env:/app/.env
    ports:
      - "3000:5173"
    env_file:
      - .env

  landingpage:
    build:
      context: ./landingpage
      dockerfile: Dockerfile
    volumes:
      - ./landingpage:/app
      - /app/node_modules          # Mesma regra para landingpage
      - ./.env:/app/.env
    ports:
      - "3002:5173"
    env_file:
      - .env
