version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    ports:
      - "3001:3001"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    env_file:
      - .env

  landingpage:
    build:
      context: ./landingpage
      dockerfile: Dockerfile
    volumes:
      - ./landingpage:/app
      - /app/node_modules 
      - ./.env:/app/.env
    ports:
      - "3002:4000"
    env_file:
      - .env
