version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app                # Código da aplicação
      - ./.env:/app/.env             # Variáveis de ambiente
    ports:
      - "3001:3000"                  # Porta host:container (Nest expõe 3000)
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app              # Código da aplicação
      - ./.env:/app/.env             # Variáveis de ambiente
    ports:
      - "3000:5173"                  # Porta host:container (Vite expõe 5173)
    env_file:
      - .env

  landingpage:
    build:
      context: ./landingpage
      dockerfile: Dockerfile
    volumes:
      - ./landingpage:/app           # Código da aplicação
      - ./.env:/app/.env             # Variáveis de ambiente
    ports:
      - "3002:5173"                  # Porta host:container (Vite expõe 5173)
    env_file:
      - .env
