version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "3001:3001"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    env_file:
      - .env

  landing:
    build:
      context: .
      dockerfile: landing/Dockerfile
    volumes:
      - ./landing:/app
      - ./.env:/app/.env
    ports:
      - "3002:3000"
    env_file:
      - .env
